sudo: required
dist: trusty

language: node_js
node_js:
  - "5"
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y python-pip
  - sudo pip install pandoc-numbering
  - sudo apt-get install -y ghc
  - sudo apt-get install -y cabal-install
  - cabal update
  - cabal install cabal-install
  - mkdir pandoc-build
  - cd pandoc-build
  - ~/.cabal/bin/cabal sandbox init
  - ~/.cabal/bin/cabal install pandoc-crossref
#  - ~/.cabal/bin/cabal install pandoc-citeproc
  - wget "http://http.us.debian.org/debian/pool/main/h/haskell-pandoc-citeproc/pandoc-citeproc_0.9-1_amd64.deb"
  - sudo dpkg -i pandoc-citeproc_0.9-1_amd64.deb
  - PATH=${PATH}:`pwd`/.cabal-sandbox/bin
  - cd ../
before_script:
- npm install -g shelljs
- npm install yargs
script: shjs ./build.js -g
branches:
  only:
  - master
env:
  global:
    secure: oDfqyuXQWVwqGHmZxp8kkViEkAa1lh4jH3TzuE9iLKrGk8YgGq0gq+519n+/WXFY9Iv+yHVfJFFV/wRyrE+NKMRuVguVeU+gyqrTTYbIxOGaJon3WkjyBaRMUjdqzQ70sKik+0XO/eKvXwJm800+ubvIk8b2liQRT7ZZ4fx8SH35XpQg4ILREJIJlK/AM3pv5FE8pGGs77YIn/TlpSLLesQLIFZey3jnhgRjVFLxXTQ9i++IycrzXEeB+utPpyWXG8JoHHIf3TUKM3n2ajeAwVzlyEnEUROw2dPeVP45a5kfpP9NcaM797wXNe7R8SkJCIqu3OCA8p/NwamuVTRlrqUjRLmWkgdUak5AIzdDjmKXCr3Vm+4+90/XT9vkb39sZupjpqyVkB7V7C5IyfTKWsF5F8TUcadj18yqCX/Bm3Cxw058oQwn5Rx+f6zvh7ZJ3IZEpBeBjSqKI82/UrOoaoCWnfop1x+MrmB0Ktqe5WP9QWUJxjaFzBhw7GiUgecOnfP/oCcBH2sUVh0f6p8Mjdjga5wkgFHRu3290v0DUEjcbywtCOFD0PNezI/8KMIadzrLPm4lDjfOBYa2Er/PMCe6S7UBE39GGU8iaUs0pucCkNF7PgxC8Izi7HvTr6hsSeBHE2+Jtm8uOay7WxbInP0ijH2SdLIgUMn90HTKbEY=

# comment
# citeproc isn't working https://github.com/jgm/pandoc-citeproc/issues/153
# this didn't work https://github.com/lambdabot/lambdabot/issues/90
